services:
  postgres:
    image: postgres:16-alpine
    container_name: commerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/00-create-dbs.sql:/docker-entrypoint-initdb.d/00-create-dbs.sql:ro
      -
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commerce -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
