spring:
  application:
    name: delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_delivery
    username: commerce
    password: commerce
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: delivery

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
