spring:
  main:
    web-application-type: none

  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
    auto-offset-reset: earliest
  producer:
    acks: all
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/