spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092

telemetry:
  topics:
    snapshots: telemetry.snapshots.v1
    hub-events: telemetry.hubs.v1
  consumers:
    snapshots-group-id: analyzer-snapshots
    hub-events-group-id: analyzer-hub-events

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
