spring:
  application:
    name: collector

collector:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

grpc:
  server:
    port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
