spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
      separator: ";"
      encoding: UTF-8

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    hub:
      hub-group-id: aggregator-group
      auto-offset-reset: earliest
      auto-commit: false
      poll-timeout-ms: 200
    snapshot:
      snapshot-group-id: analyzer-snapshots-group
      auto-offset-reset: earliest
      auto-commit: false
      poll-timeout-ms: 200
  topics:
    snapshots: telemetry.snapshots.v1
    hub-events: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/